name: Bug Report
description: Report a reproducible bug or regression.
title: "[Bug] <short description>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please complete the following to help us debug.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief summary of the bug
      placeholder: e.g. "Crash on clicking Submit button"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Include code snippets or screenshots if helpful
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: Describe what actually happened
  - type: input
    id: version
    attributes:
      label: Environment / Version Info
      placeholder: e.g. Chrome 125, Node.js 18, MacOS
