name: Documentation Request
description: Request improvements or additions to documentation.
title: "[Docs] <short description>"
labels: [documentation]
body:
  - type: input
    id: section
    attributes:
      label: Affected Section
      placeholder: e.g. "API Reference → Authentication"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: |
        Describe what’s missing, outdated, or unclear in the docs.
    validations:
      required: true
