name: Protect Main Branch

on:
  push:
    branches: [main]

jobs:
  protect-main:
    if: github.repository != 'mpointner/java-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Branch Protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const branch = 'main';
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ["Verify code compiling and tests running through"]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                dismiss_stale_reviews: false,
                require_code_owner_reviews: false,
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              required_linear_history: false,
              block_creations: false,
              required_conversation_resolution: true
            });

      - name: Delete this workflow
        run: |
          rm -f .github/workflows/branch-protection.yml
          git config user.name "Michael Pointner"
          git config user.email "mpointner@tgm.ac.at"
          git add -u
          git commit -m "Cleanup branch protection workflow"
          git push
