name: Continuous Integration (CI)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Verify code compiling and tests running through
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project (Compile and test code)
        run: ./gradlew build -x jar # Jar not needed in the CI, will be build in the CD
